/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    black_hole_black_hole_blackoutside_0: THREE.Mesh
    black_hole_black_hole_blackoutside_0_1: THREE.Mesh
    black_hole_black_hole_blackoutside_0_2: THREE.Mesh
    black_hole_black_hole_light3_0: THREE.Mesh
    black_hole_black_hole_light2_0: THREE.Mesh
    black_hole_black_hole_light1_0: THREE.Mesh
    black_hole_black_hole_distortion_0: THREE.Mesh
    black_hole_black_hole_center_0: THREE.Mesh
    black_hole_ring_ring_0: THREE.Mesh
    black_hole_ring_ring2_0: THREE.Mesh
    black_hole_ring_ring2_0_1: THREE.Mesh
    black_hole_ring_ring2_0_2: THREE.Mesh
    black_hole_ring_ring2_0_3: THREE.Mesh
    Planet_Planet_0: THREE.Mesh
  }
  materials: {
    black_hole_blackoutside: THREE.MeshPhysicalMaterial
    black_hole_light3: THREE.MeshStandardMaterial
    black_hole_light2: THREE.MeshStandardMaterial
    black_hole_light1: THREE.MeshStandardMaterial
    black_hole_distortion: THREE.MeshPhysicalMaterial
    black_hole_center: THREE.MeshPhysicalMaterial
    ring: THREE.MeshStandardMaterial
    ring2: THREE.MeshStandardMaterial
    Planet: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/black_hole.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  geometry={nodes.black_hole_black_hole_blackoutside_0.geometry}
                  material={materials.black_hole_blackoutside}
                />
                <mesh
                  geometry={nodes.black_hole_black_hole_blackoutside_0_1.geometry}
                  material={materials.black_hole_blackoutside}
                />
                <mesh
                  geometry={nodes.black_hole_black_hole_blackoutside_0_2.geometry}
                  material={materials.black_hole_blackoutside}
                />
                <mesh
                  geometry={nodes.black_hole_black_hole_light3_0.geometry}
                  material={materials.black_hole_light3}
                />
                <mesh
                  geometry={nodes.black_hole_black_hole_light2_0.geometry}
                  material={materials.black_hole_light2}
                />
                <mesh
                  geometry={nodes.black_hole_black_hole_light1_0.geometry}
                  material={materials.black_hole_light1}
                />
                <mesh
                  geometry={nodes.black_hole_black_hole_distortion_0.geometry}
                  material={materials.black_hole_distortion}
                />
                <mesh
                  geometry={nodes.black_hole_black_hole_center_0.geometry}
                  material={materials.black_hole_center}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.black_hole_ring_ring_0.geometry} material={materials.ring} />
                <mesh
                  geometry={nodes.black_hole_ring_ring2_0.geometry}
                  material={materials.ring2}
                />
                <mesh
                  geometry={nodes.black_hole_ring_ring2_0_1.geometry}
                  material={materials.ring2}
                />
                <mesh
                  geometry={nodes.black_hole_ring_ring2_0_2.geometry}
                  material={materials.ring2}
                />
                <mesh
                  geometry={nodes.black_hole_ring_ring2_0_3.geometry}
                  material={materials.ring2}
                />
              </group>
              <group
                position={[30802.89648, 2286.71704, 136477.79688]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}>
                <mesh geometry={nodes.Planet_Planet_0.geometry} material={materials.Planet} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/black_hole.glb')
